services:
  - type: web
    name: ecommerce-api
    env: python
    buildCommand: ./build.sh
    startCommand: cd ecommerce_backend && exec gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
